name: Waka Readme

on:
  schedule:
    # Runs at minute 0 past every 8th hour.
    - cron: '0 */8 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_USERNAME: ${{ secrets.GH_USERNAME }}
          COMMIT_EMAIL: ${{ secrets.GH_EMAIL }} 
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"